# Generated by Django 6.0.2 on 2026-03-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='mood_tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
